<?php

namespace OC\ShopBundle\Repository;

/**
 * BookingssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingssRepository extends \Doctrine\ORM\EntityRepository
{
}
