<?php

namespace OC\ShopBundle\Repository;

/**
 * TryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TryRepository extends \Doctrine\ORM\EntityRepository
{
}
