services:
   oc_shop.envoimail:
    class: OC\ShopBundle\Services\EnvoiMail
    
    
    #oc_shop.stripe:
        #class: OC\ShopBundle\Services\StripeClient
        #autowire: true
        #arguments:
            #- '%stripe_secret_key%'
            #- "@ar_louvre.outilsresa"
            #- '@session'